//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiAlmacen.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipo
    {
        public int iIdEquipo { get; set; }
        public int iIdMarca { get; set; }
        public int iIdModelo { get; set; }
        public string vchNoSerie { get; set; }
        public Nullable<int> iExistencia { get; set; }
        public string vchProveedor { get; set; }
        public int iIdAlmacen { get; set; }
    
        public virtual Almacen Almacen { get; set; }
        public virtual Marca Marca { get; set; }
        public virtual Modelo Modelo { get; set; }
    }
}
